apiVersion: apps/v1
kind: Deployment
metadata:
  name: restcrud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restcrud
  template:
    metadata:
      labels:
        app: restcrud
    spec:
      containers:
        - name: restcrud
          image: restcrud
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: restcrud-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
  selector:
    app: restcrud